package com.lite_k8s.compose;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.*;

class ServiceDefinitionEntityTest {

    @Test
    @DisplayName("ServiceDefinition 생성 시 id가 UUID로 자동 생성된다")
    void idIsAutoGenerated() {
        ServiceDefinition def = new ServiceDefinition();
        assertThat(def.getId()).isNotNull().hasSize(36);
    }

    @Test
    @DisplayName("ServiceDefinition은 필수 필드를 가진다")
    void hasRequiredFields() {
        ServiceDefinition def = ServiceDefinition.builder()
                .name("quvi-operia")
                .composeYaml("services:\n  quvi:\n    image: ghcr.io/daquv-qv/quvi:latest")
                .envProfileId("profile-1")
                .nodeNames(List.of("gcp-operia"))
                .build();

        assertThat(def.getName()).isEqualTo("quvi-operia");
        assertThat(def.getComposeYaml()).contains("ghcr.io/daquv-qv/quvi");
        assertThat(def.getEnvProfileId()).isEqualTo("profile-1");
        assertThat(def.getNodeNames()).containsExactly("gcp-operia");
    }

    @Test
    @DisplayName("기본값: status=DRAFT, nodeNames=빈리스트")
    void hasDefaults() {
        ServiceDefinition def = new ServiceDefinition();
        assertThat(def.getStatus()).isEqualTo(ServiceDefinition.Status.DRAFT);
        assertThat(def.getNodeNames()).isEmpty();
        assertThat(def.getCreatedAt()).isNotNull();
    }

    @Test
    @DisplayName("name이 없으면 validate에서 예외")
    void validateFailsWithoutName() {
        ServiceDefinition def = ServiceDefinition.builder().name(null).composeYaml("x").build();
        assertThatThrownBy(def::validate)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("name");
    }

    @Test
    @DisplayName("composeYaml이 없으면 validate에서 예외")
    void validateFailsWithoutYaml() {
        ServiceDefinition def = ServiceDefinition.builder().name("test").composeYaml(null).build();
        assertThatThrownBy(def::validate)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("composeYaml");
    }
}
