package com.lite_k8s.envprofile;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

class EnvProfileAuditLogTest {

    @Test
    @DisplayName("EnvProfileAuditLog 생성 시 id, timestamp 자동 생성")
    void idAndTimestampAutoGenerated() {
        EnvProfileAuditLog log = new EnvProfileAuditLog();
        assertThat(log.getId()).isNotNull().hasSize(36);
        assertThat(log.getTimestamp()).isNotNull();
    }

    @Test
    @DisplayName("EnvProfileAuditLog는 필수 필드를 가진다")
    void hasRequiredFields() {
        EnvProfileAuditLog log = EnvProfileAuditLog.builder()
                .profileId("p1")
                .profileName("db-operia")
                .action(EnvProfileAuditLog.Action.CREATED)
                .actor("admin")
                .build();

        assertThat(log.getProfileId()).isEqualTo("p1");
        assertThat(log.getProfileName()).isEqualTo("db-operia");
        assertThat(log.getAction()).isEqualTo(EnvProfileAuditLog.Action.CREATED);
        assertThat(log.getActor()).isEqualTo("admin");
    }

    @Test
    @DisplayName("EnvProfileAuditLog에 changedKeys, beforeHash, afterHash 저장 가능")
    void hasAuditFields() {
        EnvProfileAuditLog log = EnvProfileAuditLog.builder()
                .profileId("p1")
                .profileName("db-operia")
                .action(EnvProfileAuditLog.Action.ENTRY_UPDATED)
                .actor("admin")
                .changedKeys("DB_PASSWORD")
                .beforeHash("abc123")
                .afterHash("def456")
                .build();

        assertThat(log.getChangedKeys()).isEqualTo("DB_PASSWORD");
        assertThat(log.getBeforeHash()).isEqualTo("abc123");
        assertThat(log.getAfterHash()).isEqualTo("def456");
    }

    @Test
    @DisplayName("Action enum에 모든 필요한 값이 있다")
    void actionEnumValues() {
        assertThat(EnvProfileAuditLog.Action.values()).containsExactlyInAnyOrder(
                EnvProfileAuditLog.Action.CREATED,
                EnvProfileAuditLog.Action.UPDATED,
                EnvProfileAuditLog.Action.DELETED,
                EnvProfileAuditLog.Action.ENTRY_ADDED,
                EnvProfileAuditLog.Action.ENTRY_UPDATED,
                EnvProfileAuditLog.Action.ENTRY_DELETED,
                EnvProfileAuditLog.Action.REFERENCED
        );
    }
}
