package com.lite_k8s.envprofile;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

class EnvProfileEntityTest {

    @Test
    @DisplayName("EnvProfile 생성 시 id가 UUID로 자동 생성된다")
    void idIsAutoGenerated() {
        EnvProfile profile = new EnvProfile();
        assertThat(profile.getId()).isNotNull();
        assertThat(profile.getId()).hasSize(36);
    }

    @Test
    @DisplayName("EnvProfile은 name, type, description, enabled, createdAt 필드를 ��진다")
    void hasRequiredFields() {
        EnvProfile profile = EnvProfile.builder()
                .name("db-operia-postgres")
                .type(EnvProfile.ProfileType.DATABASE)
                .description("Operia PostgreSQL 접속 정보")
                .build();

        assertThat(profile.getName()).isEqualTo("db-operia-postgres");
        assertThat(profile.getType()).isEqualTo(EnvProfile.ProfileType.DATABASE);
        assertThat(profile.getDescription()).isEqualTo("Operia PostgreSQL 접속 정보");
    }

    @Test
    @DisplayName("EnvProfile의 기본값: enabled=true, type=DATABASE")
    void hasDefaults() {
        EnvProfile profile = new EnvProfile();
        assertThat(profile.isEnabled()).isTrue();
        assertThat(profile.getType()).isEqualTo(EnvProfile.ProfileType.DATABASE);
        assertThat(profile.getCreatedAt()).isNotNull();
    }

    @Test
    @DisplayName("EnvProfile에 name이 없으면 validate에서 예외가 발생한다")
    void validateFailsWithoutName() {
        EnvProfile profile = EnvProfile.builder()
                .name(null)
                .build();

        assertThatThrownBy(profile::validate)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("name");
    }
}
