package com.lite_k8s.envprofile;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

class EnvProfileEntryEntityTest {

    @Test
    @DisplayName("EnvProfileEntry 생성 시 id가 UUID로 자동 생성된다")
    void idIsAutoGenerated() {
        EnvProfileEntry entry = new EnvProfileEntry();
        assertThat(entry.getId()).isNotNull();
        assertThat(entry.getId()).hasSize(36);
    }

    @Test
    @DisplayName("EnvProfileEntry는 profileId, key, value, secret 필드를 가진다")
    void hasRequiredFields() {
        EnvProfileEntry entry = EnvProfileEntry.builder()
                .profileId("profile-1")
                .key("DB_HOST")
                .value("112.187.198.214")
                .secret(false)
                .build();

        assertThat(entry.getProfileId()).isEqualTo("profile-1");
        assertThat(entry.getKey()).isEqualTo("DB_HOST");
        assertThat(entry.getValue()).isEqualTo("112.187.198.214");
        assertThat(entry.isSecret()).isFalse();
    }

    @Test
    @DisplayName("EnvProfileEntry의 secret 기본값은 false이다")
    void defaultSecretIsFalse() {
        EnvProfileEntry entry = new EnvProfileEntry();
        assertThat(entry.isSecret()).isFalse();
    }

    @Test
    @DisplayName("EnvProfileEntry에 key가 없으면 validate에서 예외가 발생한다")
    void validateFailsWithoutKey() {
        EnvProfileEntry entry = EnvProfileEntry.builder()
                .profileId("profile-1")
                .key(null)
                .value("some-value")
                .build();

        assertThatThrownBy(entry::validate)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("key");
    }
}
