package com.lite_k8s.update;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

class ImageWatchEntityTest {

    @Test
    @DisplayName("1. ImageWatchEntity를 생성하면 id가 UUID로 자동 생성된다")
    void idIsAutoGenerated() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).hasSize(36); // UUID format
    }

    @Test
    @DisplayName("2. ImageWatchEntity는 image, tag, containerPattern, maxUnavailable 필드를 가진다")
    void hasRequiredFields() {
        ImageWatchEntity entity = ImageWatchEntity.builder()
                .image("ghcr.io/silicao3o/exercise-auth")
                .tag("v1.0")
                .containerPattern("exercise-auth.*")
                .maxUnavailable(2)
                .build();

        assertThat(entity.getImage()).isEqualTo("ghcr.io/silicao3o/exercise-auth");
        assertThat(entity.getTag()).isEqualTo("v1.0");
        assertThat(entity.getContainerPattern()).isEqualTo("exercise-auth.*");
        assertThat(entity.getMaxUnavailable()).isEqualTo(2);
    }

    @Test
    @DisplayName("3. ImageWatchEntity는 enabled, createdAt 필드를 가진다")
    void hasEnabledAndCreatedAt() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.isEnabled()).isTrue(); // 기본값 true
        assertThat(entity.getCreatedAt()).isNotNull();
    }

    @Test
    @DisplayName("4. ImageWatchEntity에 image가 없으면 validate에서 예외가 발생한다")
    void validateFailsWithoutImage() {
        ImageWatchEntity entity = ImageWatchEntity.builder()
                .image(null)
                .containerPattern("test.*")
                .build();

        assertThatThrownBy(entity::validate)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("image");
    }

    @Test
    @DisplayName("5. ImageWatchEntity의 tag 기본값은 latest이다")
    void defaultTagIsLatest() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getTag()).isEqualTo("latest");
    }

    @Test
    @DisplayName("ImageWatchEntity에 nodeName 필드가 있다 (기본 null = 전체 노드)")
    void hasNodeNameField() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getNodeName()).isNull();

        ImageWatchEntity withNode = ImageWatchEntity.builder()
                .image("ghcr.io/org/app")
                .nodeName("worker-1")
                .build();
        assertThat(withNode.getNodeName()).isEqualTo("worker-1");
    }

    @Test
    @DisplayName("ImageWatchEntity에 ghcrToken 필드가 있다 (기본 null)")
    void hasGhcrTokenField() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getGhcrToken()).isNull();

        ImageWatchEntity withToken = ImageWatchEntity.builder()
                .image("ghcr.io/org/app")
                .ghcrToken("ghp_abc123")
                .build();
        assertThat(withToken.getGhcrToken()).isEqualTo("ghp_abc123");
    }
}
