package com.lite_k8s.update;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.*;

class ImageWatchEntityTest {

    @Test
    @DisplayName("1. ImageWatchEntity를 생성하면 id가 UUID로 자동 생성된다")
    void idIsAutoGenerated() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).hasSize(36);
    }

    @Test
    @DisplayName("2. ImageWatchEntity는 image, tag, containerPattern, maxUnavailable 필드를 가진다")
    void hasRequiredFields() {
        ImageWatchEntity entity = ImageWatchEntity.builder()
                .image("ghcr.io/silicao3o/exercise-auth")
                .tag("v1.0")
                .containerPattern("exercise-auth.*")
                .maxUnavailable(2)
                .build();

        assertThat(entity.getImage()).isEqualTo("ghcr.io/silicao3o/exercise-auth");
        assertThat(entity.getTag()).isEqualTo("v1.0");
        assertThat(entity.getContainerPattern()).isEqualTo("exercise-auth.*");
        assertThat(entity.getMaxUnavailable()).isEqualTo(2);
    }

    @Test
    @DisplayName("3. ImageWatchEntity는 enabled, createdAt 필드를 가진다")
    void hasEnabledAndCreatedAt() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.isEnabled()).isTrue();
        assertThat(entity.getCreatedAt()).isNotNull();
    }

    @Test
    @DisplayName("4. ImageWatchEntity에 image가 없으면 validate에서 예외가 발생한다")
    void validateFailsWithoutImage() {
        ImageWatchEntity entity = ImageWatchEntity.builder()
                .image(null)
                .containerPattern("test.*")
                .build();

        assertThatThrownBy(entity::validate)
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("image");
    }

    @Test
    @DisplayName("5. ImageWatchEntity의 tag 기본값은 latest이다")
    void defaultTagIsLatest() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getTag()).isEqualTo("latest");
    }

    @Test
    @DisplayName("ImageWatchEntity에 nodeNames 필드가 있다 (기본 빈 리스트 = 전체 노드)")
    void hasNodeNamesField() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getNodeNames()).isEmpty();

        ImageWatchEntity withNodes = ImageWatchEntity.builder()
                .image("ghcr.io/org/app")
                .nodeNames(List.of("worker-1", "worker-2"))
                .build();
        assertThat(withNodes.getNodeNames()).containsExactly("worker-1", "worker-2");
    }

    @Test
    @DisplayName("ImageWatchEntity에 pollIntervalSeconds 필드가 있다 (기본 300)")
    void hasPollIntervalSecondsField() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getPollIntervalSeconds()).isEqualTo(300);

        ImageWatchEntity withInterval = ImageWatchEntity.builder()
                .image("ghcr.io/org/app")
                .pollIntervalSeconds(60)
                .build();
        assertThat(withInterval.getPollIntervalSeconds()).isEqualTo(60);
    }

    @Test
    @DisplayName("getEffectiveGhcrToken은 레지스트리 토큰을 반환한다")
    void getEffectiveGhcrToken_FromRegistry() {
        ImageWatchEntity entity = new ImageWatchEntity();
        assertThat(entity.getEffectiveGhcrToken()).isNull();

        com.lite_k8s.envprofile.ImageRegistry registry = com.lite_k8s.envprofile.ImageRegistry.builder()
                .image("ghcr.io/org/app").ghcrToken("ghp_abc123").build();
        ImageWatchEntity withRegistry = ImageWatchEntity.builder()
                .image("ghcr.io/org/app")
                .imageRegistry(registry)
                .build();
        assertThat(withRegistry.getEffectiveGhcrToken()).isEqualTo("ghp_abc123");
    }
}
